  - _libgcc_mutex=
  - _openmp_mutex=
  - attrs=
  - automat=
  - bcrypt=
  - brotlipy=
  - bzip2=
  - ca-certificates=
  - certifi=
  - cffi=
  - cgns=
  - chardet=
  - conda=
  - conda-package-handling=
  - constantly=
  - cryptography=
  - curl=
  - cycler=
  - dbus=
  - double-conversion=
  - expat=
  - fontconfig=
  - freetype=
  - gettext=
  - gl2ps=
  - glew=
  - glib=
  - gst-plugins-base=
  - gstreamer=
  - hdf4=
  - hdf5=
  - hyperlink=
  - icu=
  - idna=
  - incremental=
  - jpeg=
  - jsoncpp=
  - kiwisolver=
  - krb5=
  - ld_impl_linux-64=
  - libarchive=
  - libblas=
  - libcblas=
  - libclang=
  - libcurl=
  - libedit=
  - libffi=
  - libgcc-ng=
  - libgfortran-ng=
  - libglu=
  - libgomp=
  - libiconv=
  - liblapack=
  - libllvm9=
  - libnetcdf=
  - libogg=
  - libopenblas=
  - libpng=
  - libprotobuf=
  - libsolv=
  - libssh2=
  - libstdcxx-ng=
  - libtheora=
  - libtiff=
  - libuuid=
  - libvorbis=
  - libwebp-base=
  - libxcb=
  - libxkbcommon=
  - libxml2=
  - lz4-c=
  - lzo=
  - mamba=
  - matplotlib-base=
  - ncurses=
  - nspr=
  - nss=
  - numpy=
  - openssl=
  - paraview=
  - pcre=
  - pip=
  - pthread-stubs=
  - pugixml=
  - pyasn1=
  - pyasn1-modules=
  - pycosat=
  - pycparser=
  - pyhamcrest=
  - pyopenssl=
  - pyparsing=
  - pysocks=
  - python=
  - python-dateutil=
  - python_abi=
  - qt=
  - readline=
  - requests=
  - ripgrep=
  - ruamel_yaml=
  - service_identity=
  - setuptools=
  - six=
  - sqlite=
  - tk=
  - tornado=
  - tqdm=
  - twisted=
  - urllib3=
  - wheel=
  - xorg-kbproto=
  - xorg-libx11=
  - xorg-libxau=
  - xorg-libxdmcp=
  - xorg-libxext=
  - xorg-xextproto=
  - xorg-xproto=
  - xz=
  - yaml=
  - zlib=
  - zope.interface=
  - zstd=
    - appdirs=
    - astunparse=
    - autopep8=
    - awkupy=
    - backcall=
    - beniget=
    - bleach=
    - bullet=
    - cached-property=
    - cfgv=
    - click=
    - configargparse=
    - datrie=
    - decorator=
    - defusedxml=
    - distlib=
    - docutils=
    - entrypoints=
    - filelock=
    - fluiddyn=
    - fluidfft=
    - fluidsim=
    - fortran-language-server=
    - gast=
    - gitdb=
    - gitpython=
    - greenlet=
    - h5netcdf=
    - h5py=
    - identify=
    - importlib-metadata=
    - inflection=
    - ipykernel=
    - ipython=
    - ipython-genutils=
    - jedi=
    - jinja2=
    - json5=
    - jsonschema=
    - jupyter-client=
    - jupyter-core=
    - jupyterlab=
    - jupyterlab-server=
    - markupsafe=
    - mistune=
    - msgpack=
    - nbconvert=
    - nbformat=
    - nodeenv=
    - notebook=
    - packaging=
    - pandas=
    - pandocfilters=
    - parso=
    - pexpect=
    - pickleshare=
    - pluggy=
    - pre-commit=
    - prometheus-client=
    - prompt-toolkit=
    - psutil=
    - ptyprocess=
    - pycodestyle=
    - pyfftw=
    - pygments=
    - pynvim=
    - pyrsistent=
    - python-jsonrpc-server=
    - python-language-server=
    - pytz=
    - pyyaml=
    - pyzmq=
    - ratelimiter=
    - send2trash=
    - setuptools-scm=
    - smmap=
    - snakemake=
    - snek5000=
    - terminado=
    - testpath=
    - toml=
    - toposort=
    - traitlets=
    - transonic=
    - ujson=
    - virtualenv=
    - wcwidth=
    - webencodings=
    - wrapt=
    - xarray=
    - zipp=
