name: Tests

on: [push, pull_request]

env:
  PIP_CACHE_DIR: ~/.cache/pip

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: ["3.8", "3.10", "3.12"]

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive
        fetch-depth: 0

    - name: Install apt packages
      run: |
        sudo apt-get update
        sudo apt-get install gfortran libopenmpi-dev ccache

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'

    - name: Verify Python environment
      run: |
        pip list
        pip cache list

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install git+https://github.com/exabl/snek5000
        pip install .[tests]

    - name: Run tests
      run: |
        source activate.sh
        pytest -s
        SNEK_DEBUG=1 pytest tests/test_penalty.py
