name: Tests

on: pull_request

env:
  PIP_CACHE_DIR: ~/.cache/pip

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        token: ${{ secrets.SNEK_ABL_PAT }}
        submodules: recursive
        fetch-depth: 0

    - name: Install apt packages
      run: |
        sudo apt-get update
        sudo apt-get install gfortran libopenmpi-dev ccache

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache pip requirements
      id: pip-cache
      uses: actions/cache@v2
      with:
        path: ${{ env.PIP_CACHE_DIR }}
        key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.*') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Verify Python environment
      run: |
        pip list
        pip cache list

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[tests]

    - name: Run tests
      run: |
        source activate.sh
        pytest -s
        SNEK_DEBUG=1 pytest tests/test_penalty.py
